#!/bin/bash

#==============================================================================
# Cleanup Script for ResNet Training Environment
#
# This script removes the log files and outputs generated by the SLURM
# submission script and the Python training script.
#
# Usage:
# 1. Save this file as 'cleanup.sh' in your project directory.
# 2. Make it executable: chmod +x cleanup.sh
# 3. Run it: ./cleanup.sh
#==============================================================================

echo "Cleaning up log and output files..."

# Use the -v (verbose) flag to show which files are being removed.
# Use the -f (force) flag to ignore nonexistent files and never prompt.
# The `find` command is safer as it won't fail if no files match the pattern.

# Remove SLURM output files (*.out)
find . -maxdepth 1 -name "*.out" -print -delete
echo "Removed SLURM .out files."

# Remove SLURM error files (*.err)
find . -maxdepth 1 -name "*.err" -print -delete
echo "Removed SLURM .err files."

# Remove the Python training log
find . -maxdepth 1 -name "*.log" -print -delete
echo "Removed Python training.log."

echo "-------------------------"
echo "Cleanup complete."
